cloud:
  aws:
    credentials:
      access-key: AKIA6QHB5G3VOPT3KE5H
      secret-key: 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
#      access-key: ENC(hrS2wfwf+Y0Y184PJB/QissDYUd2XT5r5SHa40Y3Las=)
#      secret-key: ENC(Fy3Y6CqSPzVUHUGxLwbYp4w8nOKbG9Iz7sqjHkFU4wOe8+qzGNsJAR4i+dzHhI15yHaTKjbB/Uk=)